#!/bin/sh

port=${1:-${PORT:-25566}}
heap=“384m”

echo "Starting: minecraft ${port}"
echo "server-port=${port}" >> /app/server.properties

eval "java -Xmx${heap} -Xms${heap} -jar minecraft.jar nogui &"
main_pid=$!

trap "kill $main_pid" SIGTERM
trap "kill -9 $main_pid; exit" SIGKILL
